### ISSUE TITLE
Bands - API Implementation

### ISSUE THREAD

**Issue by Moh-Zaman** [SatsumaSegment/Canvas-Compass#3]
User story:
As a dev, I want to be able to properly implement my API and be fully functional.

Acceptance Criteria:
API functions and allows the pulling of data successfully.

https://collectionapi.metmuseum.org/public/collection/v1/search?q=

**Comment by Moh-Zaman** [comment]
- [x] > * Add For Loop or For each for each object ID
- [ ] > * Implement search button feature to this API
- [ ] > * Work on other features related to this API like information gathering

**Comment by SatsumaSegment** [comment]
I gathered quite a bit of information, we can go over it in class today to see if there's anything else we need.

**Comment by Moh-Zaman** [comment]
This is now done
